services:
  client: 
    build:
      context: ./client
    environment:
      NODE_ENV: production
      NEXT_API_URL: ${SERVER_URL:-http://localhost:4000}
    ports:
      - "${CLIENT_PORT:-3000}:3000"

  server:
    build:
      context: ./server
      target: final
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - PORT=${SERVER_PORT:-4000}
    ports:
      - "${SERVER_PORT:-4000}:4000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: