services:
  server:
    build:
      context: .
      target: final
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-change_this_password}
      DB_NAME: ${DB_NAME:-football}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      JWT_EXPIRES_HOURS: ${JWT_EXPIRES_HOURS:-24}
      FOOTBALL_API_TOKEN: ${FOOTBALL_API_TOKEN}
      FOOTBALL_API_URL: ${FOOTBALL_API_URL:-https://api.football-data.org/v4}
      SERVER_PORT: ${SERVER_PORT:-4000}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-football}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-change_this_password}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-football}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
